channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.21.3
  - cffi==1.17.1
  - cloudpickle==2.2.1
  - colorama==0.4.6
  - cytoolz==0.12.2
  - dask-expr==1.1.0
  - defusedxml==0.7.1
  - distributed==2024.5.0
  - graphviz==0.20.1
  - jinja2==3.1.6
  - lightgbm==4.6.0
  - lz4==4.3.2
  - matplotlib==3.10.1
  - mmh3==5.1.0
  - numpy==1.26.4
  - pandas==2.2.3
  - pathlib==1.0.1
  - pyarrow==18.1.0
  - python-snappy==0.6.1
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - setproctitle==1.3.5
  - xxhash==3.5.0
  - zstandard==0.23.0
name: mlflow-env
